### ISSUE TITLE
Example for tests?

### ISSUE THREAD

**Issue by cah-brian-gantzler** [NullVoxPopuli/ember-msw-development#1]
This example shows how to use MSW in an application, if I only wanted to use it in tests, do you have an example of that?

I have been trying to use it in tests only and when I make a fetch to `/user/1` it is redirecting to `http://localhost:7357/user/1/tests/index.html?hidepassed` and then giving me a response of `Not found: /user/1/tests/index.html?hidepassed`

To use it in tests and not the app, there must be something more to do, but not sure what that is

NOTE: Should have added, this is an addons test, so the dummy app.

**Comment by NullVoxPopuli** [comment]
in this file:
https://github.com/NullVoxPopuli/ember-msw-development/blob/main/app/routes/application.js#L3

you could change this to:
```js
import { isTesting } from '@embroider/macros';
```

so that way MSW is only used in testing instead of "non-production" (DEBUG)

**Comment by cah-brian-gantzler** [comment]
In  the example addon repo Im doing. I didnt put MSW in the app, so dont have to if that.  This is purely a testing problem. 

Whats weird is that in the fetch to `/user/1` (in addon code) I see in the network it redirects to `http://localhost:7357/user/1/tests/index.html?hidepassed`.   Im wondering why in tests its redirecting and adding `tests/index.html?hidepassed`.

This is just a dummy addon to test MSW in addon tests as we have shared services in addons that make network calls. 

I am assuming that MSW should still be able to work under those circumstances correct? Will post the addon repo as soon I get the change so you can see what Im talking about.

**Comment by NullVoxPopuli** [comment]
gotchya, so then you want something like this: https://github.com/NullVoxPopuli/ember-data-resources/blob/main/tests/unit/find-all-test.ts#L16

>  http://localhost:7357/user/1/tests/index.html?hidepassed. Im wondering why in tests its redirecting and adding tests/index.html?hidepassed.

I don't know why that'd be happening

**Comment by cah-brian-gantzler** [comment]
I think thats exactly it. Thanks, will look at this and see if I can find whats different in the way I set it up.

**Comment by cah-brian-gantzler** [comment]
Looked at this example, couldnt really see anything different. 

Booted my addon again and it just now works. No idea 😄

**Comment by cah-brian-gantzler** [comment]
Dont know if you would be interested in experimenting with this. https://github.com/miragejs/miragejs/issues/1013

**Comment by NullVoxPopuli** [comment]
maybe. I haven't had a need to implement data-mocking/factories from scratch in a long time, and if I do, first thing I'd want to try is msw-data -- failing _that_, I'd look at mirage support, but I have no idea when that could happen in the next couple years :sweat_smile:

**Comment by cah-brian-gantzler** [comment]
Mirage has a lot of nice features that are currently missing from MSW-Data

**Comment by NullVoxPopuli** [comment]
:shrug: mirage also uses pretender, which is unacceptable to me :sweat_smile:

**Comment by cah-brian-gantzler** [comment]
:) You didnt read the PR. This allows Mirage to use MSW

**Comment by NullVoxPopuli** [comment]
is unmerged :p

**Comment by cah-brian-gantzler** [comment]
Yes, I was asking if you had time to experiment with it to see if there are any gaps or things not accounted for. Definitely beta. Understand if you dont have time. Just making you aware. Will let you know when it is merged

My tests all run except for a weird intermittent async problem when tests arent waiting correctly. Trying to get a few other people to try it out to see if its specific to my tests or a larger issue. (Which would appreciate help tracking down)

**Comment by NullVoxPopuli** [comment]
oh!!! I can review probably this weekend <3

sorry, I misunderstood
